# Generated by Django 5.1.4 on 2026-09-23 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "favorites",
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("descricao", models.TextField()),
                ("extra_info", models.TextField(blank=True)),
                ("aluguel", models.DecimalField(decimal_places=2, max_digits=10)),
                ("negociavel", models.BooleanField(default=False)),
                (
                    "condominio_valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("condominio_incluido", models.BooleanField(default=False)),
                (
                    "iptu_valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("iptu_incluido", models.BooleanField(default=False)),
                ("outras_taxas", models.TextField(blank=True)),
                (
                    "garantia",
                    models.CharField(
                        choices=[
                            ("CAUCAO", "Caução"),
                            ("FIADOR", "Fiador"),
                            ("SEM_GARANTIA", "Sem garantia"),
                            ("SEGURO_FIANCADO", "Seguro Fiançado"),
                        ],
                        default="SEM_GARANTIA",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("PUBLICADO", "Publicado"),
                            ("PAUSADO", "Pausado"),
                            ("EXPIRADO", "Expirado"),
                            ("ALUGADO", "Alugado"),
                        ],
                        db_index=True,
                        default="RASCUNHO",
                        max_length=20,
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("favorites_count", models.PositiveIntegerField(default=0)),
                ("messages_count", models.PositiveIntegerField(default=0)),
                ("quality_score", models.FloatField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Anúncio",
                "verbose_name_plural": "Anúncios",
                "db_table": "listings",
            },
        ),
        migrations.CreateModel(
            name="ListingView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "listing_views",
            },
        ),
    ]
