# Generated by Django 5.1.4 on 2026-09-23 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="listings.listing",
            ),
        ),
        migrations.AddField(
            model_name="listingview",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="listings.listing",
            ),
        ),
        migrations.AddField(
            model_name="listingview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "published_at"], name="listings_status_23e807_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["owner", "status"], name="listings_owner_i_7626df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["aluguel"], name="listings_aluguel_628af0_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["quality_score"], name="listings_quality_c79cc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(
                fields=["user", "created_at"], name="favorites_user_id_9cc509_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "listing")},
        ),
        migrations.AddIndex(
            model_name="listingview",
            index=models.Index(
                fields=["listing", "viewed_at"], name="listing_vie_listing_62e2ac_idx"
            ),
        ),
    ]
