# Generated by Django 5.1.4 on 2026-09-23 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NOVO_FAVORITO", "Novo Favorito"),
                            ("NOVA_MENSAGEM", "Nova Mensagem"),
                            ("ANUNCIO_EXPIRADO", "Anúncio Expirado"),
                            ("OTP_ENVIADO", "OTP Enviado"),
                            ("BOAS_VINDAS", "Boas-vindas"),
                            ("SISTEMA", "Sistema"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensagem", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("lida", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
