# Generated by Django 5.1.4 on 2026-09-23 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("FOTO", "Foto"), ("VIDEO", "Vídeo")], max_length=10
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("url_optimized", models.URLField(blank=True, max_length=500)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                ("public_id", models.CharField(max_length=300, unique=True)),
                ("nome", models.CharField(blank=True, max_length=200)),
                ("tamanho_mb", models.FloatField()),
                ("largura", models.PositiveIntegerField(blank=True, null=True)),
                ("altura", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duracao_segundos",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("formato", models.CharField(blank=True, max_length=20)),
                ("is_highlight", models.BooleanField(default=False)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Mídia",
                "verbose_name_plural": "Mídias",
                "db_table": "media",
                "ordering": ["ordem", "created_at"],
            },
        ),
    ]
