# Generated by Django 5.1.4 on 2026-09-23 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0002_initial"),
        ("media", "0001_initial"),
        ("properties", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageQuota",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="storage_quota",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("fotos_count", models.PositiveIntegerField(default=0)),
                ("videos_count", models.PositiveIntegerField(default=0)),
                ("total_mb_used", models.FloatField(default=0.0)),
                ("total_mb_limit", models.FloatField(default=1024.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "storage_quotas",
            },
        ),
        migrations.AddField(
            model_name="media",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media",
                to="listings.listing",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(
                fields=["user", "tipo"], name="media_user_id_4dce66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["property"], name="media_propert_a005d6_idx"),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(
                fields=["listing", "is_highlight"], name="media_listing_4d5d45_idx"
            ),
        ),
    ]
