# Generated by Django 5.1.4 on 2026-09-23 18:21

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CASA", "Casa"),
                            ("APARTAMENTO", "Apartamento"),
                            ("KITNET", "Kitnet"),
                            ("COMODO", "Cômodo"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("area_m2", models.FloatField(help_text="Área em metros quadrados")),
                ("cep", models.CharField(max_length=9)),
                ("logradouro", models.CharField(max_length=300)),
                ("numero", models.CharField(max_length=20)),
                ("bairro", models.CharField(max_length=200)),
                ("cidade", models.CharField(db_index=True, max_length=200)),
                ("estado", models.CharField(db_index=True, max_length=2)),
                ("complemento", models.CharField(blank=True, max_length=200)),
                ("referencia", models.CharField(blank=True, max_length=300)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("features", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("ATIVO", "Ativo"),
                            ("INATIVO", "Inativo"),
                            ("ALUGADO", "Alugado"),
                        ],
                        db_index=True,
                        default="RASCUNHO",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Imóvel",
                "verbose_name_plural": "Imóveis",
                "db_table": "properties",
            },
        ),
        migrations.CreateModel(
            name="PropertyRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("quartos", "Quartos"),
                            ("suites", "Suítes"),
                            ("banheiros", "Banheiros"),
                            ("salas", "Salas"),
                            ("garagem", "Garagem"),
                            ("varandas", "Varandas"),
                            ("outros", "Outros"),
                        ],
                        max_length=30,
                    ),
                ),
                ("quantidade", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "property_rooms",
            },
        ),
    ]
