# Generated by Django 5.1.4 on 2026-09-23 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propertyroom",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="properties.property",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["owner", "status"], name="properties_owner_i_56c14d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["cidade", "estado"], name="properties_cidade_930353_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["tipo"], name="properties_tipo_7cb6e9_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["created_at"], name="properties_created_abda95_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propertyroom",
            unique_together={("property", "tipo")},
        ),
    ]
